Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/07/2023
Var
// Seção de Declarações das variáveis 
Numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Numero <- 0
Repita
escreva (numero)
numero <- numero +1
ate (numero = 10)

Fimalgoritmo