Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/07/2023
Var
// Seção de Declarações das variáveis 
BOOLEANA:LOGICO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
BOOLEANA<- VERDADEIRO
ESCREVAL ("O VALOR DA VARIAVEL BOOLEANA É",BOOLEANA)


Fimalgoritmo